name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: hdfc-playground

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Secret Scanning using GitLeaks
      - name: Run GitLeaks Secret Scan
        uses: gitleaks/gitleaks-action@v2

      # Filesystem Vulnerability Scan using Trivy
      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install Flutter Dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t hdfc-playground .

      # Scan Docker Image using Trivy
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hdfc-playground:latest
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag hdfc-playground:latest ${{ steps.login-ecr.outputs.registry }}/hdfc-playground:latest

      # Push Docker Image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/hdfc-playground:latest