name: Security Scan

on:
  push:
    branches:
      - main

jobs:

  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Start SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:lts-community
          sleep 60

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=flutter-security \
          -Dsonar.sources=lib \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=admin \
          -Dsonar.password=admin

      - name: Save SonarQube Report
        run: |
          curl -s "http://localhost:9000/api/measures/component?component=flutter-security&metricKeys=bugs,vulnerabilities,code_smells,coverage" \
          -u admin:admin > sonar-report.json

      - name: Install Gitleaks
        run: |
          go install github.com/zricethezav/gitleaks/v8@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect \
          --source . \
          --report-format json \
          --report-path gitleaks-report.json || true

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: json
          output: trivy-report.json
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            sonar-report.json
            gitleaks-report.json
            trivy-report.json


  report:
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Download Security Reports
        uses: actions/download-artifact@v4
        with:
          name: security-reports

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate Human Readable Security Report
        run: |

          echo "======================================="
          echo "        SECURITY SUMMARY REPORT"
          echo "======================================="

          echo ""
          echo "SONARQUBE RESULTS"
          jq -r '.component.measures[] |
          "| " + .metric + " | " + .value + " |"' sonar-report.json

          echo ""
          echo "GITLEAKS RESULTS"

          if [ -s gitleaks-report.json ]; then
            jq -r '.[] |
            "| " + .RuleID + " | " + .File + " | line " + (.StartLine|tostring) + " |"' gitleaks-report.json
          else
            echo "No secrets detected"
          fi

          echo ""
          echo "TRIVY RESULTS"

          jq -r '.Results[].Vulnerabilities[]? |
          " |      " + .PkgName +
          " |      " + .VulnerabilityID +
          " |      " + .Severity +
          " | CVSS " + (.CVSS.nvd.V3Score|tostring) +
          " |      "' trivy-report.json